packages:
  - packages/*
  - internal/*
  - examples/*

catalog:
  eslint: ^9.32.0
  prettier: ^3.5.3
  tsup: ^8.3.5
  typescript: ^5.9.2
  vite: ^6.3.5
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.1
  zod: 4.1.5

minimumReleaseAge: 1440
