packages:
  - packages/*
  - internal/*
  - examples/*
catalog:
  eslint: ^9.32.0
  typescript: ^5.8.3
  prettier: ^3.5.3
  zod: ^4.0.0
  vite: ^6.3.5
  vitest: ^3.2.1
  vite-plugin-dts: ^4.5.4
  tsup: ^8.3.5
minimumReleaseAge: 1440
