packages:
  - packages/*
  - examples/*
  - internal/*
onlyBuiltDependencies:
  - vitest-evals
catalog:
  eslint: ^9.28.0
  typescript: ^5.8.3
  prettier: ^3.5.3
  zod: ^3.25.49
  vite: ^6.3.5
  vitest: ^3.2.1
  vite-plugin-dts: ^4.5.4
  tsup: ^8.3.5
