packages:
  - packages/*
  - internal/*
  - examples/*

catalog:
  eslint: ^9.32.0
  prettier: ^3.5.3
  tsup: ^8.3.5
  typescript: ^5.8.3
  vite: ^6.3.5
  vite-plugin-dts: ^4.5.4
  vitest: ^4.0.0
  zod: 4.1.5

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "next@16.0.9"
  - "react@19.2.3"
  - "react-dom@19.2.3"
