name: Slack Notification

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Notify about merged PRs
        id: notify-pr-merged
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "#proj-rudder",
              "text": "PR Merged for @axiomhq/ai: *${{ github.event.head_commit.message || github.event.pull_request.title }}* :tada:\n<${{ github.event.head_commit.url || github.event.pull_request.html_url }}|View Changes>"
            }
